name: Caching and Artifacts
on:
  workflow_dispatch:
jobs:
  use-axios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4  # Use v4 or the latest version that supports Node.js 20
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Use Axios
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require('axios');
            const res = await axios('https://icanhazdadjoke.com/', { headers: { Accept: 'text/plain' } })
            console.log(res.data)